name: example

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests with Gradle
        run: ./gradlew test
        env:
          MESSAGE: Hello World!
