name: Welcome to CI/CD

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      
  steps:
    -./gradlew test
    with:
      message:
          Hello
