name: example

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Run tests with Gradle
        run: ./gradlew test
        env:
          MESSAGE: Hello World!
